### PR TITLE
chore(i18n): add more languages

### PR DESCRIPTION
**Pull request by Yoiber071**
Add Transifex Working Group languages.

New language codes: it_IT,pt_PT,de_DE

@feanil 
@natabene

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Yoiber071!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by e0d** [comment]
@mphilbrick211 tests run.

**Comment by e0d** [comment]
@Yoiber071 looks like there are test failures.

**Comment by mphilbrick211** [comment]
Hi @Yoiber071 just checking in to flag the failing tests need to be re-run.

**Comment by felipemontoya** [comment]
Tests run.

**Comment by Yoiber071** [comment]
Hi @mphilbrick211, Sorry for the late response, I've fixed the lint failures, and is ready to be tested again.

**Comment by mphilbrick211** [comment]
@hurtstotouchfire this is ready for review / merge!

**Comment by mphilbrick211** [comment]
Friendly ping on this, @hurtstotouchfire!

**Comment by mphilbrick211** [comment]
Hi @hurtstotouchfire - just checking in on this :)

**Comment by mphilbrick211** [comment]
Hi @openedx/2u-aperture! Could someone take a look at this and merge if all looks good? Thanks!

**Comment by jsnwesson** [comment]
Adding this to team Aperture's kanban for code review! I'll be the go-to for Profile open-source PRs, so if you need to tag me for anything that's ready to be reviewed, by all means 😁

**Review by jsnwesson — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@Yoiber071 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-profile&entry.867055334=https://github.com/openedx/frontend-app-profile/pull/689&entry.1484655318=https://github.com/Yoiber071&entry.752974735=2023-02-14+17:43&entry.1917517419=2023-07-03+17:20&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
