### PR TITLE
Yamaha olive.1

### PR DESCRIPTION
**Pull request by elisreginazoche**

### CODE REVIEW

**Comment by mphilbrick211** [comment]
Hi @elisreginazoche! Thank you for your contribution! Once you submit your [CLA](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base) and re-run the tests, the check should turn green. Please let me know if you have any questions.

**Comment by mphilbrick211** [comment]
> Hi @elisreginazoche! Thank you for your contribution! Once you submit your [CLA](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base) and re-run the tests, the check should turn green. Please let me know if you have any questions.

Hi @elisreginazoche! Friendly ping on this :)

**Comment by nedbat** [comment]
This looks like a mistake, based on the branch name Olive.1.   @elisreginazoche Feel free to open a new pull request if needed.

**Comment by openedx-webhooks** [comment]
@elisreginazoche Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-profile&entry.867055334=https://github.com/openedx/frontend-app-profile/pull/711&entry.1484655318=https://github.com/elisreginazoche&entry.752974735=2023-03-14+13:12&entry.1917517419=2023-03-25+13:42&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
