### PR TITLE
feat: upgrade react router to v6

### PR DESCRIPTION
**Pull request by Syed-Ali-Abbas-Zaidi**
## Ticket
[React Router Upgrade to v6](https://github.com/openedx/platform-roadmap/issues/276).

## Description
This PR upgrades React Router from `v5` to `v6`.

### CODE REVIEW

**Comment by MaxFrank13** [comment]
Thanks for doing this! As a result of #718, we have updated how the `Routes` are configured in this MFE

**Comment by justinhynes** [comment]
@Syed-Ali-Abbas-Zaidi There are still some conflicts in this PR. If we can get those resolved I can prioritize reviewing and merging the changes. Thanks!

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
> @Syed-Ali-Abbas-Zaidi There are still some conflicts in this PR. If we can get those resolved I can prioritize reviewing and merging the changes. Thanks!

I have resolved the conflicts.

**Review by justinhynes — APPROVED** [review]
LGTM. I have also merged the internal PR for the profile MFE.

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
> LGTM. I have also merged the internal PR for the profile MFE.

We need to merge this [edge-PR](https://github.com/edx/edge-internal/pull/568) too, so that it can also be deployed on edge as well.

**Pull request merged**
