### PR TITLE
feat: Fields visibility and visibility forms (palm.master)

### PR DESCRIPTION
**Pull request by vladislavkeblysh**
- Fixed the display of fields in a user's profile when viewing it from our own account to another user's profile that was just created (by default, the fields Full name, Location, and Certificates (if any) are displayed).
- Fixed the display of empty fields in a user's profile when viewing it from our own account to another user's profile that was just created. Fields that are not filled in will not be displayed (previously, if a field was not filled in, the field name was displayed, but not the value).
- Fixed the behavior of forms for a newly created user. Previously, if you changed the value of one field to Just me for the first time, the values of other fields were also reset to Just me. Now, only the value of the edited field is changed.

Screenshot 2023-10-10 at 15 09 45
Screenshot 2023-10-10 at 15 10 11
Screenshot 2023-10-10 at 15 10 02

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @vladislavkeblysh!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by e0d** [comment]
@vladislavkeblysh seeing some linting fallures.

**Comment by e0d** [comment]
@vladislavkeblysh seeing some linting failures.

**Comment by vladislavkeblysh** [comment]
@e0d Fixed

**Comment by justinhynes** [comment]
I'll be taking a look at this today.

**Review by justinhynes — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@vladislavkeblysh 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-profile&entry.867055334=https://github.com/openedx/frontend-app-profile/pull/865&entry.1484655318=https://github.com/vladislavkeblysh&entry.752974735=2023-10-10+11:45&entry.1917517419=2023-11-08+18:46&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
