### PR TITLE
feat: tutor-mfe compatiblilty for `atlas pull` | FC-0012

### PR DESCRIPTION
**Pull request by OmarIthawi**
Similar to https://github.com/openedx/frontend-app-communications/pull/187.

## Changes

 - install atlas
 - remove `--filter` to pull all languages by default
 - use ATLAS_OPTIONS to allow custom `--filter`
 - include frontend-platform in `atlas pull`

## Refs
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which implements the [Translation Infrastructure update OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by brian-smith-tcril — APPROVED** [review]

**Comment by brian-smith-tcril** [comment]
@openedx/2u-aperture I plan on merging this in the next half hour, please let me know if I should hold off

**Review by justinhynes — APPROVED** [review]
Thanks for the heads up!

**Comment by openedx-webhooks** [comment]
@OmarIthawi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-profile&entry.867055334=https://github.com/openedx/frontend-app-profile/pull/959&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2024-01-29+15:36&entry.1917517419=2024-01-30+17:19&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
